mv 000_OnlyLongestPepsTranslated_Drosophila_melanogaster.BDGP6.cds.pep.all.fa.txt         Drosophila.pep.txt 
mv 000_OnlyLongestPEP_Ciona_intestinalis.KH.pep.all.fa.txt                                Ciona.pep.txt      
mv 000_OnlyLongestPEP_Xenopus_tropicalis.JGI_4.2.pep.all.fa                               Xenopus.pep.txt    
mv 000_OnlyLongestPEP_Gallus_gallus-E102.GRCg6a.pep.all.fa.txt                            Chicken.pep.txt    
mv 000_OnlyLongestPEP_Homo_sapiens-E102.GRCh38.pep.all.fa.txt                             Human.pep.txt      
mv 000_OnlyLongestPEP_Danio_rerio.GRCz10.pep.all.fa                                       Zebra.pep.txt      
mv 000_OnlyLongestPEP_Tetraodon_nigroviridis.TETRAODON8.pep.all.fa.txt                    Tetraodon.pep.txt  
mv 000_OnlyLongestPEP_Gasterosteus_aculeatus.BROADS1.pep.all.fa.txt                       Stickleback.pep.txt
mv 000_OnlyLongestPEP_Oryzias_latipes.MEDAKA1.pep.all.fa                                  Medaka.pep.txt     
mv 000_OnlyLongestCDStrans_Drosophila_melanogaster.BDGP6.cds.all.fa.txt                   Drosophila.cds.txt
mv 000_OnlyLongestCDS_Ciona_intestinalis.KH.cds.all.fa.txt                                Ciona.cds.txt
mv 000_OnlyLongestCDS_Xenopus_tropicalis.JGI_4.2.cds.all.fa                               Xenopus.cds.txt
mv 000_OnlyLongestCDS_Gallus_gallus-E102.GRCg6a.cds.all.fa.txt                            Chicken.cds.txt
mv 000_OnlyLongestCDS_Homo_sapiens-E102.GRCh38.cds.all.fa.txt                             Human.cds.txt
mv 000_OnlyLongestCDS_Danio_rerio.GRCz10.cds.all.fa                                       Zebra.cds.txt
mv 000_OnlyLongestCDS_Tetraodon_nigroviridis.TETRAODON8.cds.all.fa.txt                    Tetraodon.cds.txt
mv 000_OnlyLongestCDS_Gasterosteus_aculeatus.BROADS1.cds.all.fa.txt                       Stickleback.cds.txt
mv 000_OnlyLongestCDS_Oryzias_latipes.MEDAKA1.cds.all.fa                                  Medaka.cds.txt
